name: WhatsApp Bot Deploy

on:
  workflow_dispatch:
    inputs:
      SESSION_DATA:
        description: 'mAQ1WL6S#RZWa5Crxv_rXmN-P94qV1MRZ53FK6EhcP38KXjTHqZM'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Write session.json
      run: echo "${{ github.event.inputs.SESSION_DATA }}" | base64 -d > session.json

    - name: Start bot
      run: node bot.js
